function x_dot = SymDynamicsEuler5DoF(r1,r2,r3,v1,v2,v3,theta1,theta2,theta3,w1,w2,T1,T2,T3,mass,L,I,max_thrust)
%SymDynamicsEuler5DoF
%    X_DOT = SymDynamicsEuler5DoF(R1,R2,R3,V1,V2,V3,THETA1,THETA2,THETA3,W1,W2,T1,T2,T3,MASS,L,I,MAX_THRUST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Jan-2025 22:18:36

t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
t7 = sin(theta3);
t8 = 1.0./I;
t9 = 1.0./mass;
t10 = 1.0./t6;
x_dot = [v1;v2;v3;t9.*(T1.*max_thrust.*t3+T3.*max_thrust.*t4.*t6+T2.*max_thrust.*t6.*t7);t9.*(T2.*max_thrust.*(t2.*t4-t3.*t5.*t7)-T3.*max_thrust.*(t2.*t7+t3.*t4.*t5)+T1.*max_thrust.*t5.*t6);-t9.*(-T2.*max_thrust.*(t4.*t5+t2.*t3.*t7)+T3.*max_thrust.*(t5.*t7-t2.*t3.*t4)+T1.*max_thrust.*t2.*t6)-9.81e+2./1.0e+2;t4.*t10.*w2+t7.*t10.*w1;t4.*w1-t7.*w2;-t3.*t4.*t10.*w2-t3.*t7.*t10.*w1;
    L.*T3.*max_thrust.*t8;
    -L.*T2.*max_thrust.*t8];
end
