function xdot = SymDynamics3DoF(r1,r2,v1,v2,theta1,w1,thrust1,gimbal1,mass,L,I)
%SymDynamics3DoF
%    XDOT = SymDynamics3DoF(R1,R2,V1,V2,THETA1,W1,THRUST1,GIMBAL1,MASS,L,I)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Nov-2024 02:07:37

t2 = gimbal1+theta1;
t3 = 1.0./mass;
xdot = [v1;v2;t3.*thrust1.*cos(t2);t3.*thrust1.*sin(t2)-9.81e+2./1.0e+2;w1;-(L.*thrust1.*sin(gimbal1))./I];
end
