function j_b = SymUJacobian3DoF(r1,r2,v1,v2,theta1,w1,thrust1,gimbal1,mass,L,I)
%SymUJacobian3DoF
%    J_B = SymUJacobian3DoF(R1,R2,V1,V2,THETA1,W1,THRUST1,GIMBAL1,MASS,L,I)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    25-Nov-2024 00:53:43

t2 = gimbal1+theta1;
t4 = 1.0./I;
t6 = 1.0./mass;
t3 = cos(t2);
t5 = sin(t2);
j_b = reshape([0.0,0.0,t3.*t6,t5.*t6,0.0,-L.*t4.*sin(gimbal1),0.0,0.0,-t5.*t6.*thrust1,t3.*t6.*thrust1,0.0,-L.*t4.*thrust1.*cos(gimbal1)],[6,2]);
end
