function x_dot = SymDynamicsQuat6DoF_localrot_noumag(in1,in2,L,in4,alpha,g)
%SymDynamicsQuat6DoF_localrot_noumag
%    X_DOT = SymDynamicsQuat6DoF_localrot_noumag(IN1,IN2,L,IN4,ALPHA,G)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Aug-2025 05:22:37

I1 = in4(1,:);
I2 = in4(2,:);
I3 = in4(3,:);
T1 = in2(1,:);
T2 = in2(2,:);
T3 = in2(3,:);
m1 = in1(14,:);
tau1 = in2(4,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
theta4 = in1(10,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(11,:);
w2 = in1(12,:);
w3 = in1(13,:);
t2 = conj(T1);
t3 = conj(T2);
t4 = conj(T3);
t5 = T1.*theta2;
t6 = T2.*theta1;
t7 = T1.*theta3;
t8 = T3.*theta1;
t9 = T1.*theta4;
t10 = T2.*theta3;
t11 = T3.*theta2;
t12 = T2.*theta4;
t13 = T3.*theta4;
t17 = -I3;
t18 = 1.0./m1;
t14 = t2.*theta1;
t15 = t3.*theta2;
t16 = t4.*theta3;
t19 = -t5;
t20 = -t8;
t21 = -t10;
t22 = t6+t13+t19;
t23 = t7+t12+t20;
t24 = t9+t11+t21;
t25 = t14+t15+t16;
mt1 = [v1;v2;v3;t18.*(t22.*theta2-t23.*theta3+t25.*theta1+t24.*theta4);t18.*(-t22.*theta1+t23.*theta4+t24.*theta3+t25.*theta2);-g+t18.*(t23.*theta1+t22.*theta4-t24.*theta2+t25.*theta3);(theta2.*w3)./2.0-(theta3.*w2)./2.0+(theta4.*w1)./2.0;theta1.*w3.*(-1.0./2.0)+(theta3.*w1)./2.0+(theta4.*w2)./2.0;(theta1.*w2)./2.0-(theta2.*w1)./2.0+(theta4.*w3)./2.0;w1.*conj(theta1).*(-1.0./2.0)-(w2.*conj(theta2))./2.0-(w3.*conj(theta3))./2.0;(tau1+w2.*w3.*(I2+t17))./I1;(L.*T3-w1.*w3.*(I1+t17))./I2;-(L.*T2-w1.*w2.*(I1-I2))./I3];
mt2 = [-alpha.*sqrt(T1.^2+T2.^2+T3.^2)-alpha.*sqrt(tau1.^2)];
x_dot = [mt1;mt2];
end
