function x_dot = SymDynamicsEuler6DoF(r1,r2,r3,v1,v2,v3,theta1,theta2,theta3,w1,w2,w3,T1,T2,T3,gamma1,mass,L,I1,I2,I3,max_thrust)
%SymDynamicsEuler6DoF
%    X_DOT = SymDynamicsEuler6DoF(R1,R2,R3,V1,V2,V3,THETA1,THETA2,THETA3,W1,W2,W3,T1,T2,T3,GAMMA1,MASS,L,I1,I2,I3,MAX_THRUST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    29-Dec-2024 21:01:44

t2 = cos(gamma1);
t3 = cos(theta1);
t4 = cos(theta2);
t5 = cos(theta3);
t6 = sin(theta1);
t7 = sin(theta2);
t8 = sin(theta3);
t9 = -I3;
t10 = 1.0./mass;
t11 = 1.0./t7;
mt1 = [v1;v2;v3;t2.*t10.*(T1.*max_thrust.*t4+T3.*max_thrust.*t5.*t7+T2.*max_thrust.*t7.*t8);t2.*t10.*(T2.*max_thrust.*(t3.*t5-t4.*t6.*t8)-T3.*max_thrust.*(t3.*t8+t4.*t5.*t6)+T1.*max_thrust.*t6.*t7);-t2.*t10.*(-T2.*max_thrust.*(t5.*t6+t3.*t4.*t8)+T3.*max_thrust.*(t6.*t8-t3.*t4.*t5)+T1.*max_thrust.*t3.*t7)-9.81e+2./1.0e+2;t5.*t11.*w3+t8.*t11.*w2;t5.*w2-t8.*w3;w1-t4.*t5.*t11.*w3-t4.*t8.*t11.*w2;
    (sin(gamma1).*sqrt(abs(T1.*max_thrust).^2+abs(T2.*max_thrust).^2+abs(T3.*max_thrust).^2)+w2.*w3.*(I2+t9))./I1;
    -(w1.*w3.*(I1+t9)-L.*T3.*max_thrust.*t2)./I2];
mt2 = [(w1.*w2.*(I1-I2)-L.*T2.*max_thrust.*t2)./I3];
x_dot = [mt1;mt2];
end
