function x_dot = SymDynamicsQuat6DoF_localrot_alphabeta(in1,in2,L,in4,alpha_T,g)
%SymDynamicsQuat6DoF_localrot_alphabeta
%    X_DOT = SymDynamicsQuat6DoF_localrot_alphabeta(IN1,IN2,L,IN4,alpha_T,G)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Aug-2025 11:42:48

I1 = in4(1,:);
I2 = in4(2,:);
I3 = in4(3,:);
T1 = in2(1,:);
alpha1 = in2(2,:);
beta1 = in2(3,:);
m1 = in1(14,:);
tau1 = in2(4,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
theta4 = in1(10,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(11,:);
w2 = in1(12,:);
w3 = in1(13,:);
t2 = conj(T1);
t3 = conj(alpha1);
t4 = cos(alpha1);
t5 = conj(beta1);
t6 = cos(beta1);
t7 = sin(alpha1);
t8 = sin(beta1);
t13 = -I3;
t14 = 1.0./m1;
t9 = cos(t3);
t10 = cos(t5);
t11 = sin(t3);
t12 = sin(t5);
t15 = T1.*t7.*theta1;
t16 = T1.*t7.*theta3;
t17 = T1.*t7.*theta4;
t18 = T1.*t8.*theta1;
t19 = T1.*t8.*theta2;
t20 = T1.*t8.*theta4;
t21 = T1.*t4.*t6.*theta2;
t22 = T1.*t4.*t6.*theta3;
t23 = T1.*t4.*t6.*theta4;
t24 = t2.*t11.*theta2;
t25 = t2.*t12.*theta3;
t26 = -t16;
t27 = -t18;
t28 = -t21;
t29 = t2.*t9.*t10.*theta1;
t30 = t15+t20+t28;
t31 = t17+t22+t27;
t32 = t19+t23+t26;
t33 = t24+t25+t29;
mt1 = [v1;v2;v3;t14.*(t30.*theta2-t31.*theta3+t33.*theta1+t32.*theta4);t14.*(-t30.*theta1+t31.*theta4+t32.*theta3+t33.*theta2);-g+t14.*(t31.*theta1+t30.*theta4-t32.*theta2+t33.*theta3);(theta2.*w3)./2.0-(theta3.*w2)./2.0+(theta4.*w1)./2.0;theta1.*w3.*(-1.0./2.0)+(theta3.*w1)./2.0+(theta4.*w2)./2.0;(theta1.*w2)./2.0-(theta2.*w1)./2.0+(theta4.*w3)./2.0;w1.*conj(theta1).*(-1.0./2.0)-(w2.*conj(theta2))./2.0-(w3.*conj(theta3))./2.0;(tau1+w2.*w3.*(I2+t13))./I1;-(w1.*w3.*(I1+t13)-L.*T1.*t8)./I2;-(L.*T1.*t7-w1.*w2.*(I1-I2))./I3];
mt2 = [-T1.*alpha_T-alpha_T.*tau1];
x_dot = [mt1;mt2];
end
