function j_b = SymUJacobianEuler6DoF(r1,r2,r3,v1,v2,v3,theta1,theta2,theta3,w1,w2,w3,T1,T2,T3,gamma1,mass,L,I1,I2,I3,max_thrust)
%SymUJacobianEuler6DoF
%    J_B = SymUJacobianEuler6DoF(R1,R2,R3,V1,V2,V3,THETA1,THETA2,THETA3,W1,W2,W3,T1,T2,T3,GAMMA1,MASS,L,I1,I2,I3,MAX_THRUST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    29-Dec-2024 21:01:47

t2 = conj(T1);
t3 = conj(T2);
t4 = conj(T3);
t5 = cos(gamma1);
t6 = conj(max_thrust);
t7 = cos(theta1);
t8 = cos(theta2);
t9 = cos(theta3);
t10 = sin(gamma1);
t11 = sin(theta1);
t12 = sin(theta2);
t13 = sin(theta3);
t14 = T1.*max_thrust;
t15 = T2.*max_thrust;
t16 = T3.*max_thrust;
t20 = 1.0./I1;
t21 = 1.0./I2;
t22 = 1.0./I3;
t23 = 1.0./mass;
t17 = abs(t14);
t18 = abs(t15);
t19 = abs(t16);
t24 = t7.*t9;
t25 = t7.*t13;
t26 = t9.*t11;
t27 = t11.*t13;
t28 = t17.^2;
t29 = t18.^2;
t30 = t19.^2;
t31 = t8.*t27;
t32 = t8.*t24;
t33 = t8.*t25;
t34 = t8.*t26;
t35 = -t31;
t36 = -t32;
t37 = t25+t34;
t38 = t26+t33;
t41 = t28+t29+t30;
t39 = t24+t35;
t40 = t27+t36;
t42 = 1.0./sqrt(t41);
mt1 = [0.0,0.0,0.0,max_thrust.*t5.*t8.*t23,max_thrust.*t5.*t11.*t12.*t23,-max_thrust.*t5.*t7.*t12.*t23,0.0,0.0,0.0,(t10.*t17.*t20.*t42.*(t6.*t14+max_thrust.*t2.*t6).*1.0./sqrt(t2.*t6.*t14))./2.0,0.0,0.0,0.0,0.0,0.0,max_thrust.*t5.*t12.*t13.*t23,max_thrust.*t5.*t23.*t39,max_thrust.*t5.*t23.*t38,0.0,0.0,0.0,(t10.*t18.*t20.*t42.*(t6.*t15+max_thrust.*t3.*t6).*1.0./sqrt(t3.*t6.*t15))./2.0,0.0,-L.*max_thrust.*t5.*t22,0.0,0.0,0.0,max_thrust.*t5.*t9.*t12.*t23,-max_thrust.*t5.*t23.*t37,-max_thrust.*t5.*t23.*t40,0.0,0.0,0.0,(t10.*t19.*t20.*t42.*(t6.*t16+max_thrust.*t4.*t6).*1.0./sqrt(t4.*t6.*t16))./2.0,L.*max_thrust.*t5.*t21,0.0,0.0,0.0,0.0,-t10.*t23.*(t8.*t14+t9.*t12.*t16+t12.*t13.*t15)];
mt2 = [-t10.*t23.*(-t16.*t37+t15.*t39+t11.*t12.*t14),t10.*t23.*(-t15.*t38+t16.*t40+t7.*t12.*t14),0.0,0.0,0.0,(t5.*t20)./t42,-L.*t10.*t16.*t21,L.*t10.*t15.*t22];
j_b = reshape([mt1,mt2],12,4);
end
