function xdot = SymDynamics3DoF(r1,r2,v1,v2,theta1,w1,thrust1,gimbal1,mass,L,I,max_thrust)
%SymDynamics3DoF
%    XDOT = SymDynamics3DoF(R1,R2,V1,V2,THETA1,W1,THRUST1,GIMBAL1,MASS,L,I,MAX_THRUST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    16-Dec-2024 22:34:50

t2 = gimbal1+theta1;
t3 = 1.0./mass;
xdot = [v1;v2;max_thrust.*t3.*thrust1.*cos(t2);max_thrust.*t3.*thrust1.*sin(t2)-9.81e+2./1.0e+2;w1;-(L.*max_thrust.*thrust1.*sin(gimbal1))./I];
end
