function xdot = SymDynamics3DoF_mass_convexified_noumag(t,in2,in3,L,I,alpha)
%SymDynamics3DoF_mass_convexified_noumag
%    XDOT = SymDynamics3DoF_mass_convexified_noumag(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-May-2025 00:26:28

theta1 = in2(5,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
v1 = in2(3,:);
v2 = in2(4,:);
w1 = in2(6,:);
z1 = in2(7,:);
t2 = cos(theta1);
t3 = sin(theta1);
xdot = [v1;v2;t2.*thrust_accel1-t3.*thrust_accel2;t2.*thrust_accel2+t3.*thrust_accel1-9.81e-3;w1;-(L.*thrust_accel2.*exp(z1))./I;-alpha.*sqrt(thrust_accel1.^2+thrust_accel2.^2)];
end
