function j_a = SymXJacobianEuler5DoF(r1,r2,r3,v1,v2,v3,theta1,theta2,theta3,w1,w2,T1,T2,T3,mass,L,I,max_thrust)
%SymXJacobianEuler5DoF
%    J_A = SymXJacobianEuler5DoF(R1,R2,R3,V1,V2,V3,THETA1,THETA2,THETA3,W1,W2,T1,T2,T3,MASS,L,I,MAX_THRUST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    16-Dec-2024 22:22:36

t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
t7 = sin(theta3);
t11 = 1.0./mass;
t8 = t3.^2;
t9 = t4.*w2;
t10 = t7.*w1;
t12 = t2.*t4;
t13 = t2.*t7;
t14 = t4.*t5;
t15 = t5.*t7;
t16 = 1.0./t6;
t17 = t16.^2;
t18 = t3.*t15;
t19 = t3.*t12;
t20 = t3.*t13;
t21 = t3.*t14;
t22 = -t18;
t23 = -t19;
t24 = t13+t21;
t25 = t14+t20;
t26 = t12+t22;
t27 = t15+t23;
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t11.*(-T2.*max_thrust.*t25+T3.*max_thrust.*t27+T1.*max_thrust.*t2.*t6),t11.*(-T3.*max_thrust.*t24+T2.*max_thrust.*t26+T1.*max_thrust.*t5.*t6),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t11.*(-T1.*max_thrust.*t6+T3.*max_thrust.*t3.*t4+T2.*max_thrust.*t3.*t7),t11.*(T1.*max_thrust.*t3.*t5+T2.*max_thrust.*t6.*t15+T3.*max_thrust.*t6.*t14),-t11.*(T1.*max_thrust.*t2.*t3+T2.*max_thrust.*t6.*t13+T3.*max_thrust.*t6.*t12),-t3.*t9.*t17-t3.*t10.*t17,0.0,t9+t10+t8.*t9.*t17+t8.*t10.*t17,0.0,0.0,0.0,0.0];
mt2 = [0.0,t11.*(T2.*max_thrust.*t4.*t6-T3.*max_thrust.*t6.*t7),-t11.*(T2.*max_thrust.*t24+T3.*max_thrust.*t26),-t11.*(T3.*max_thrust.*t25+T2.*max_thrust.*t27),t4.*t16.*w1-t7.*t16.*w2,-t9-t10,-t3.*t4.*t16.*w1+t3.*t7.*t16.*w2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7.*t16,t4,-t3.*t7.*t16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4.*t16,-t7,-t3.*t4.*t16,0.0,0.0];
j_a = reshape([mt1,mt2],11,11);
end
