function [x_dot] = Dynamics_nDoF(x_current, u_current, vehicle, dof)
%DYNAMICS_NDOF Calculates the dynamics for any model given by dof
%   Calculate the state derivative for a model described by dof at the
%   current state and control for the given vehicle.
    if dof == DoF.planar3DoF
        x_dot = SymDynamics3DoF(...
            x_current(dof.ir(1)),x_current(dof.ir(2)),...
            x_current(dof.iv(1)),x_current(dof.iv(2)),...
            x_current(dof.itheta(1)),...
            x_current(dof.iw(1)),...
            u_current(dof.ithrust(1)), u_current(end), ...
            vehicle.m, vehicle.L, vehicle.I, vehicle.max_thrust);
    elseif dof == DoF.euler5DoF
        x_dot = SymDynamicsEuler5DoF(...
            x_current(dof.ir(1)),x_current(dof.ir(2)),x_current(dof.ir(3)),...
            x_current(dof.iv(1)),x_current(dof.iv(2)),x_current(dof.iv(3)),...
            x_current(dof.itheta(1)),x_current(dof.itheta(2)),x_current(dof.itheta(3)),...
            x_current(dof.iw(1)),x_current(dof.iw(2)),...
            u_current(dof.ithrust(1)), u_current(dof.ithrust(2)), u_current(dof.ithrust(3)), ...
            vehicle.m, vehicle.L, vehicle.I, vehicle.max_thrust);
    elseif dof == DoF.quat5DoF
        x_dot = SymDynamicsQuat5DoF(...
            x_current(dof.ir(1)),x_current(dof.ir(2)),x_current(dof.ir(3)),...
            x_current(dof.iv(1)),x_current(dof.iv(2)),x_current(dof.iv(3)),...
            x_current(dof.itheta(1)),x_current(dof.itheta(2)),x_current(dof.itheta(3)),x_current(dof.itheta(4)),...
            x_current(dof.iw(1)),x_current(dof.iw(2)),...
            u_current(dof.ithrust(1)), u_current(dof.ithrust(2)), u_current(dof.ithrust(3)), ...
            vehicle.m, vehicle.L, vehicle.I, vehicle.max_thrust);
    elseif dof == DoF.euler6DoF
        x_dot = SymDynamicsEuler6DoF(...
            x_current(dof.ir(1)),x_current(dof.ir(2)),x_current(dof.ir(3)),...
            x_current(dof.iv(1)),x_current(dof.iv(2)),x_current(dof.iv(3)),...
            x_current(dof.itheta(1)),x_current(dof.itheta(2)),x_current(dof.itheta(3)),...
            x_current(dof.iw(1)),x_current(dof.iw(2)),x_current(dof.iw(3)),...
            u_current(dof.ithrust(1)), u_current(dof.ithrust(2)), u_current(dof.ithrust(3)), u_current(end), ...
            vehicle.m, vehicle.L, vehicle.I, vehicle.I, vehicle.I, vehicle.max_thrust);
    elseif dof == DoF.quat6DoF
        x_dot = SymDynamicsQuat6DoF(...
            x_current(dof.ir(1)),x_current(dof.ir(2)),x_current(dof.ir(3)),...
            x_current(dof.iv(1)),x_current(dof.iv(2)),x_current(dof.iv(3)),...
            x_current(dof.itheta(1)),x_current(dof.itheta(2)),x_current(dof.itheta(3)),x_current(dof.itheta(4)),...
            x_current(dof.iw(1)),x_current(dof.iw(2)),x_current(dof.iw(3)),...
            u_current(dof.ithrust(1)), u_current(dof.ithrust(2)), u_current(dof.ithrust(3)), u_current(end), ...
            vehicle.m, vehicle.L, vehicle.I, vehicle.max_thrust);
    end
end

